"""
Django settings for s4d_webapp project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Als dit project commercieel was, moest de Secret_key voor deployment uit de settings gehaald worden (environment var.)
SECRET_KEY = '^9k@9i5mca5%56$oe-jmnfuzjwgrl*ye2kr$f^0k8oye59ml)i'

# SECURITY WARNING: don't run with debug turned on in production!
#Debug = True for production, False when it's deployed.
DEBUG = True

#For Deployment: Allow our webapp in Allowed_hosts
ALLOWED_HOSTS = ['weder.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    # Eigen apps
    'website.apps.WebsiteConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'storages',
    # is voor het maken van een nette registratie page voor bootstrap.
    # Dit zijn standaard Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 's4d_webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 's4d_webapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'nl-nl'  # 'en-us' veranderd naar nl-nl

TIME_ZONE = 'CET'  # Amsterdam Timezone ingesteld

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# Static_Root toegevoegd; voor Deployment met Heroku
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# wanneer je je website gaan deployen veranderen deze locaties.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# hier vertellen we welke css framework we willen gebruiken voor de crispy template.
CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'web-home'
LOGIN_URL = 'login'


# Hier geven wij django toestemming om onze google mail te gebruiken
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# deze gegevens kunnen nog worden verborgen m.b.v. environment variables
EMAIL_HOST_USER = 'djangos4d@gmail.com'
EMAIL_HOST_PASSWORD = 'udlinxzdpodxidtp'


#s3 management
AWS_ACCESS_KEY_ID= 'AKIAWB5PETYGJWGPH272'
AWS_SECRET_ACCESS_KEY= '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'
AWS_STORAGE_BUCKET_NAME= 'django-weder-files-2'

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

#Heroku settings
django_heroku.settings(locals())