# Generated by Django 3.0.6 on 2020-05-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_post_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reward',
            new_name='beloning',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titel',
        ),
    ]
