# Generated by Django 3.0.6 on 2020-05-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200527_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='website.Phone'),
        ),
    ]
