# Generated by Django 3.0.6 on 2020-05-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200527_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='beschrijving',
        ),
    ]
