# Generated by Django 3.0.6 on 2020-05-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200527_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
