# Generated by Django 3.0.6 on 2020-05-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200527_1405'),
        ('website', '0008_auto_20200527_1457'),
    ]

    operations = [
    ]
