# Generated by Django 3.0.6 on 2020-05-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_merge_20200527_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
    ]
