# Generated by Django 3.0.6 on 2020-05-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200528_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titel',
        ),
    ]
