# Generated by Django 3.0.6 on 2020-05-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200528_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(choices=[('keuze 1 pik', 'keuze 1 pik'), ('keuze 2 pik', 'keuze 2 pik'), ('keuze 3 pik', 'keuze 3 pik')], to='website.Category'),
        ),
    ]
