# Generated by Django 3.0.6 on 2020-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200528_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('Klusjes', 'Klusjes'), ('Uitlaatservice', 'Uitlaatservice'), ('Boodschappen', 'Boodschappen')], default=True),
        ),
    ]
