# Generated by Django 3.0.6 on 2020-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20200528_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('Klusjes', 'Klusjes'), ('Uitlaatservice', 'Uitlaatservice'), ('Boodschappen', 'Boodschappen'), ('Overig', 'Overig')], default=True),
        ),
    ]
