# Generated by Django 3.0.6 on 2020-05-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200528_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
