# Generated by Django 3.0.6 on 2020-06-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favourite',
        ),
    ]
