# Generated by Django 3.0.6 on 2020-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
