# Generated by Django 3.0.5 on 2020-06-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200608_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='adres',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locatie',
            field=models.TextField(choices=[('Arnhem-Noord', 'Arnhem-Noord'), ('Arnhem-Centrum', 'Arnhem-Centrum'), ('Arnhem-Zuid', 'Arnhem-Zuid'), ('Nijmegen-Noord', 'Nijmegen-Noord'), ('Nijmegen-Centrum', 'Nijmegen-Centrum'), ('Nijmegen-Zuid', 'Nijmegen-Zuid'), ('Overig', 'Overig')], default=True),
        ),
    ]
