# Generated by Django 3.0.6 on 2020-05-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200530_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telefoonnummer',
            field=models.CharField(blank=True, help_text='Vul 06-, +316- of Huis- nummer in', max_length=12),
        ),
    ]
