# Generated by Django 3.0.6 on 2020-05-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200527_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='users.Phone'),
        ),
    ]
