# Generated by Django 3.0.6 on 2020-05-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='users.Phone'),
        ),
    ]
