# Generated by Django 3.0.6 on 2020-05-27 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200527_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='users.Phone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(default=False, max_length=250),
        ),
    ]
