# Generated by Django 3.0.6 on 2020-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200527_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
